### ISSUE TITLE
【讨论】函数自动柯里化符号

### ISSUE THREAD

**Issue by mwc** [JSCIG/es-discuss#17]
使用 * 可以声明一个生成器函数：
```
function * foo( ) {
   ......
}
```

是否也能够通过问号来声明函数自动柯里化：
```
function ? add(a, b, c) {
  return a + b + c
}
```
然后如下调用：
```
add(1)(3)(5)
add()(1, 3)(5)
add(1, 3)(5)
```
调用时，支持问号作为占位符，类似 ramda.js 的 R.__：
```
add(1, ?, 5)(3)
```
对象字面量中声明：
```
let obj = {
  ? add(a, b, c) {
    return a + b + c
  }
}

obj.add(1)(2)(3)
```

**Comment by monkingxue** [comment]
函数 curry 的需求是什么呢？或者说什么场景需要使用一个 operator 而不是用 `curry()` 这种 util 函数呢？

**Comment by hax** [comment]
`add(1, ?, 5)` 有一份单独的 partial application 提案，它并不要求是curry（但因为和 pipeline 提案有关联，所以必须一起推进）。

**Comment by hax** [comment]
自动curry有个问题就是似乎无法和 default param 共存。

比如对于 `function ? add(a, b, c = 1)` 来说 `add(1,2)` 返回啥。

**Comment by mwc** [comment]
@hax 

返回 `4`。

参数如有默认值：
```
function ? add(a, b, c = 1) {
}
```
则 `a` 和 `b` 两个参数支持 currying，c 只支持值替换。
`add(1)` 返回偏函数，`add(1, 2)` 返回 4；通过 `add(1, 2, 10)` 覆盖 c 的默认值，得到结果 13。

**Comment by mwc** [comment]
@monkingxue 

不是什么迫切的需求，譬如 pipeline 和 partial function 一样，没有倒也无妨，基于函数高阶特性，利用现成类库或手工实现都不算难事。

**Comment by hax** [comment]
@mwc 需要注意一点，JS 里 default param 可以出现在任何位置，不一定是最后。

如果是 `function ? add(a, b=1, c)`， `add(1,2)`又返回啥呢？也是4吗？（按照你前面的描述，似乎应该是4）

从js现有的default param语义来说，`function ? add(a, b=1, c)` 其实应该等同于 `function ? add(a=undefined, b=1, c=undefined)` 。

当然我认为你描述的语义也是有道理的，ruby似乎就是如此。但js现有的default param的设计与此不太一致。

**Comment by hax** [comment]
> 提案管道与偏函数都阳光普照了

我个人觉得并没有阳光普照，而是前景不明……

**Comment by JasinYip** [comment]
> 按照你前面的描述，似乎应该是4

我理解他的意思似乎应该返回函数

**Comment by mwc** [comment]
@hax @JasinYip 

如果是 `function ? add(a, b=1, c)`， `add(1, 2)` 应返回 `**NaN**`。
这是与现有的函数语法保持一致的期望结果；
包括与使用函数式库的 curry 的结果也是一致，函数的 `length` 属性对其 curry 的实现至关重要，然而默认参数会“破坏” `length` 的真实值，因此 `function ? add(a, b=1, c)` 函数的 length 为 `**1**`， `add(1, 2)` 的调用已满足 `1` 个参数，使得它执行真实函数体并返回 `NaN`。

如果不考虑现有语法，理应是返回部分函数，等待接收最后一个参数的值，即 `add(1, 2)` 的第二个实参只是覆盖 b 的默认值，c 仍可被 curry，从字面来看是还有一个参数没有获得值。

**Comment by mwc** [comment]
以下是一个初步构思：

### constructor
```
function CurryFunction( ) {

}
```

### 声明式
```
function **?** function_name(args) {

}
```

### 表达式/匿名
```
(
  function **?** (args) {

  }
)
```

### 箭头函数柯里化
有鉴于箭头生成器（Arrow Generator），**`不支持`箭头函数柯里化**。

### 存在默认参数情况规则，包括非尾部默认参数
```
function ? add(a, b = 1, c) {

}
```
仅识别首个 default parameter 之前的参数自动柯里化，其余参数依赖调用时直接补充，不被认为是支持柯里化的参数。

## 调用
调用参考 partial function，但是建议返回 curry；
在 partial function 提案中，无需 curry 的原因无非是 pipeline 要求每个函数只能一个参数，
即问号占位符（placehold parameter）仅需一个，如果使其更具适应性，推而广之，应使其 调用后自动 currying：

### ? 占位符
```
function add(a, b, c, d) {

}

// 多个占位符
add(10, ?, 20, ?)  => return function ? (b, d) { }
```

**Comment by hax** [comment]
@mwc 你现在这个已经比较复杂了，比如混合 partial 和 curry。也不是说不行，但复杂的设计需要更强有力的动机和用例，还有正反面因素的对比。此外有很多你的设计决策（比如构造器支持curry而箭头函数不支持）需要解释原因和目的。

我先提一个比较重要的问题，如果我们有`Function.curry(f)`这样的工具方法，是否就已经够了，而不需要额外的语法。
