### ISSUE TITLE
【提案】Array.prototype.findRight

### ISSUE THREAD

**Issue by Kingwl** [JSCIG/es-discuss#19]
https://github.com/Kingwl/proposal-array-find-right

**Comment by Kingwl** [comment]
不太清楚接下来需要做啥。。。HELP

**Comment by septs** [comment]
建议去 https://es.discourse.group 发个帖子，问问有没有支持你的。

**Comment by Kingwl** [comment]
https://es.discourse.group/t/array-prototype-findright/538 Thanks!
