### ISSUE TITLE
第四次会议（2021/4/19 星期一）

### ISSUE THREAD

**Issue by Shero0311** [JSCIG/es-discuss#28]
会议主题：JSCIG 第四次会议
会议时间：2021/4/19 星期一 15:00-16:00
会议内容：TC39会议主题收集意见

- Jack 介绍 Read-only ArrayBuffer and Fixed view of ArrayBuffer for Stage 1
- class fields等 

JSCIG 第四次会议
会议时间：2021/04/19 15:00-16:00 (GMT+08:00) 中国标准时间 - 北京

点击链接入会：https://meeting.tencent.com/s/tYWh5MsPIWs0

会议 ID：357 986 814

手机一键拨号入会
+8675536550000,,357986814# (中国大陆)
+85230018898,,,2,357986814# (中国香港)

**Comment by septs** [comment]
有本次 meet 的提纲么？

**Comment by LongTengDao** [comment]
报名！是腾讯会议吗？会议ID会在什么时候发布？谢谢！

**Comment by hax** [comment]
感谢大家的参与，请移步[第五次会议](https://github.com/JSCIG/es-discuss/issues/30)
