### ISSUE TITLE
第五次会议（2021/5/14 星期五）

### ISSUE THREAD

**Issue by Shero0311** [JSCIG/es-discuss#30]
会议主题：JSCIG 第五次会议
会议时间：2021/5/14 星期五 15:00-16:00
会议内容：TC39会议主题收集意见

- https://github.com/futurist/proposal-maybe  10min

Jack
- 模式匹配
- do expression
- realms

**会议信息：**
https://meeting.tencent.com/s/IJiEGmCLtEnO
会议 ID：521 371 009

**会议录制：**
https://meeting.tencent.com/user-center/shared-record-info?id=a5e57855-0914-4159-a76e-0dea46dc2771

**Comment by futurist** [comment]
`Maybe` 类型提案：

https://github.com/futurist/proposal-maybe
