### ISSUE TITLE
JSCIG 第六次会议

### ISSUE THREAD

**Issue by Shero0311** [JSCIG/es-discuss#31]
会议主题：JSCIG 第六次会议
会议时间：2021/7/12 星期一 14:00-15:00
会议内容：TC39会议主题收集意见

会议链接：https://meeting.tencent.com/s/FUtApKdagnIK

**Comment by Kingwl** [comment]
- Array Find From Last for Stage 3 ([spec](https://tc39.es/proposal-array-find-from-last/index.html), [slides](https://kingwl.github.io/proposal-array-find-from-last-looking-for-stage-3-sides))
- String trim characters ([repo](https://github.com/Kingwl/proposal-string-trim-characters))
