### ISSUE TITLE
JSCIG 第七次会议

### ISSUE THREAD

**Issue by Shero0311** [JSCIG/es-discuss#32]
会议主题：JSCIG 第七次会议
会议时间：2021年8月31日15:00~16:00
会议内容：TC39会议主题收集意见

**Comment by hax** [comment]
本次TC39会议的议程：https://github.com/tc39/agendas/blob/master/2021/08.md

本次没有中国代表的新提案或更新，故我们的讨论议题主要是本次议程中的重点议案，包括但不限于：pipeline（要进stage2）、Fixed shape/layout objects（即struct，要进stage1），另外有时间的话可以收集下对2022年会议日程的想法。

**Comment by hax** [comment]
会议链接：https://meeting.tencent.com/dm/dapUmerjKGkl
