### ISSUE TITLE
JSCIG 第八次会议

### ISSUE THREAD

**Issue by Shero0311** [JSCIG/es-discuss#34]
会议主题：JSCIG 第七次会议
会议时间：2021年10月2x日
会议内容：TC39会议（https://github.com/tc39/agendas/blob/master/2021/10.md ）主题收集意见

**Comment by TechQuery** [comment]
我开发了一种**纯静态文件**实现的 polyfill CDN —— https://github.com/EasyWebApp/Web-polyfill

欢迎大家一起补全目录，更期待国内有**对象存储服务**羊毛的同学们 fork~

**Comment by TechQuery** [comment]
> 为了 ES 标准能更好的在生产环境落地，现征集本社区成员所在公司，是否有愿意**赞助原作者**或**搭建国内镜像**的：[wessberg/Polyfiller#40](https://github.com/wessberg/Polyfiller/issues/40)

已从 @kaiyuanshe 取得低成本云资源支持：
1. 完成墙内镜像部署：https://polyfiller.kaiyuanshe.cn/
2. 反馈上游部署方案：wessberg/Polyfiller#71
