### ISSUE TITLE
JSCIG 第十二次会议

### ISSUE THREAD

**Issue by Shero0311** [JSCIG/es-discuss#41]
会议时间：2022/03/11 14:00-15:00 (GMT+08:00) 中国标准时间 - 北京

点击链接入会，或添加至会议列表：
https://meeting.tencent.com/dm/L5LyL5jrWuX4

**Comment by hax** [comment]
会议议题：3月底TC39会议主题讨论。

重点提案：

- Type as comments 提案（Stage0->1）
- Decorator提案（Stage2->3）
- Pattern match提案（Stage1->2）

**Comment by childrentime** [comment]
会议有回放吗

**Comment by ljharb** [comment]
No, the meeting is not recorded nor permitted to be (it also hasn't happened yet).

**Comment by hax** [comment]
@ljharb I think @childrentime was asking  JSCIG meeting record (not TC39 plenary). We normally recorded JSCIG meetings so the people who missed the meeting could check it later, the record links was published in the wechat channel for chinese JS discussion group.

**Comment by hax** [comment]
感谢参与，下次会议时间将在新issue里发布。
