### ISSUE TITLE
JSCIG 第十三次会议（2022-05-31 周二）

### ISSUE THREAD

**Issue by Shero0311** [JSCIG/es-discuss#43]
会议主题：JSCIG 第十三次会议
会议时间：2022/05/31 14:00-15:00 (GMT+08:00) 

点击链接入会，或添加至会议列表：https://meeting.tencent.com/dm/oY2dypdq2RjW

**Comment by hax** [comment]
主题：讨论6月TC39会议的相关议题

主要议题
- `function.sent`提案（stage 2）更新 @hax
- ShadowRealm（stage 3）相关更新 @Jack-Works @legendecas 
- Fatal errors 提案（stage 0） @hax
- JSCIG定期会议时间讨论

初步考虑每两个月第四个周二下午2点到3点（从本次会议开始）；另一次为每两个月第三个周四下午3点到4点（4点到5点为TC39 research call的time slot B，这样可以连上，6月16日开始）。

备选议题（如果有时间）
- Type annotations相关 @hax @Jack-Works 
- `this` parameter提案（stage 0）@hax @legendecas

**Comment by hax** [comment]
感谢参会。下次会议请移步 #45 。
