### ISSUE TITLE
JSCIG 定期会议的设想

### ISSUE THREAD

**Issue by hax** [JSCIG/es-discuss#44]
我们不定期会议已经开了十多次会议了，考虑转为定期。

初步设想为每月一次：

- Time slot A 单数月第四个周二下午2点到3点（下周第十三次会议也符合该时间）；
- Time slot B 双数月第三个周四下午3点到4点。4点到5点为TC39 research call的time slot B，这样可以连上（6月16日开始）。

**Comment by shawn-yee** [comment]
有没有会议笔记呀?
希望有一些最近TC39提案讨论的精简摘要。

**Comment by hax** [comment]
@shawn-yee 有会议录像，发布在微信讨论群里。今天下午3点是新一次会议。有问题也可以在会议上提。

**Comment by hax** [comment]
自今日起开始试行定期会议。会议信息见repo的reademe。

**Comment by hax** [comment]
考虑到目前会议主要讨论者的情况，会议仍然恢复为每次单独组织。

**Comment by ljharb** [comment]
What is the current situation?

**Comment by Jack-Works** [comment]
> What is the current situation?

Currently we only hold meeting right before tc39 meeting
