### ISSUE TITLE
【提案讨论】do expression

### ISSUE THREAD

**Issue by hax** [JSCIG/es-discuss#8]
[do expression 这个提案](https://github.com/tc39/proposal-do-expressions)在stage 1上也停滞很久了（3年），在下次的会议上，有人想推它到 stage 2。见 slide：https://docs.google.com/presentation/d/14UYf30NeOd5TFZ4QJFigwBLZVotOwuQq3E-BCMIhGgk/

我认为这个slide很好地展示了 do expression 面临的核心问题，就是隐式的返回值在各种奇怪的情况下不符合程序员的预期，尤其是循环和变量声明，还有流程跳转（return/break/continue等）。这个更新提案给的解决方案就是把所有这些奇怪的情况都 ban 掉（syntax error），作为一个 Maximally minimal 的解决方案，这个方法是可行的，因为可以留待以后再讨论。不过还有另一个大问题是语法，这个slide的方案并没有涉及（仍然延续了 `do { ... }`）。

我一直认为，语义和语法是要相适配的。所以我把两个问题一起讨论。

do expression 的语义，本质上有两种解法。

### `eval`-based

一种是基于现有定义的隐式值。spec已经对每个js语句的隐式值有明确定义。这个语义目前可以通过 eval 观察到。即 `eval(code)` 所返回的就是代码`code`执行后得到的隐式值。因此我们有方案一，直接用 `eval { ... }` 语法和基于`eval(code)`的语义。

也即
```js
let result = eval {
  if (x) 1
  else 2
}
```
等价于
```js
let result = eval(`
  if (x) 1
  else 2
`)
```

如果是这样的方案，那么我们可能不需要ban掉任何东西。其中，return/break/continue等在原本提案中有争议的跳出到scope以外的行为，本来就是不允许出现在 eval 中的，所以已经自然地被 ban 掉了。剩下的循环和声明的行为，虽然可能奇怪，但是因为`eval(code)`是已经存在的东西，我们只不过提供了一个更加静态化的eval（从而有更好的浏览器优化，也不受到[CSP](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP)禁用eval的影响）。如果说一定要考虑程序员预期，得ban掉它们，那么可以留给linter去ban。

### _iife_-based

另一种是基于[IIFE](https://developer.mozilla.org/en-US/docs/Glossary/IIFE)。即把`let result = do { ... }`理解为`let result = (() => { ... })()` （这里用arrow function而不是普通函数，是因为arrow functions中`this`是lexical的，更符合do expression场景的预期）。

这种语义的好处就是所有js程序员都已经掌握，没有任何难理解之处。本质上，这种方式就是一个语法糖而已。

如果按照这种语义，我们的语法设计最好也能至少有一点能暗示 arrow function。以下使用 `{> ... }`语法作为示例（以`>`暗示arrow function）。其他语法，只要能让程序员联想到函数，也都是可以考虑的。

也即
```js
let result = {>
  if (x) return 1
  else return 2
}
```
等价于
```js
let result = (() => {
  if (x) return 1
  else return 2
})()
```

注意我们需要显式使用`return`关键字，而不再隐式使用最后一个值。（我个人不认为节约一个`return`关键字有特别巨大的价值，尤其是，如果我们使用基于iife的语义，保持和iife的语法对应是更有价值的。如果我们就是不想要`return`关键字，我们最好是回到`eval`-based方案。）

使用显式`return`，我们也不再需要ban掉任何东西（包括跳出scope的break/continue，本来就是不允许的）。

采用这种语义，也使得未来可能的扩展更容易理解。比如
```js
let result = async {>
  await delay(1000)
  return x
}
```
程序员很容易预期result应该是一个promise，因为本质上这就是一个async函数的iife结果。

### 第三种解法：一切皆表达式

最后，其实还有第三种解法。

如前所述，所有statement已经有可观测的值（通过`eval`），那么从某种程度上说，它们已经是表达式，只不过在语法上需要被进一步放宽，允许出现在所有表达式可以出现的地方。比方说，对于`if`来讲，有人就提出，可以直接支持 `let x = if (x) 1; else 2`。这当然是可以的。不过我们有两个问题，第一，这只适用于`if`，没有普遍性，更多语句怎么办（比如 `let x = do { let tmp = Math.random(); tmp * tmp }`这样简单的例子）？第二，当我们看到分号的时候，我们觉得语句应该结束了，但后面跟着的 `else` 打破了这一点。

其实这两点本质上都是一个事情，就是`;`是一个优先级更高的东西（实质上可认为是优先级最高的），表达式没法（不应）超出分号的界限。

但我们本来就有一个改变优先级的东西，那就是括号。所以可以简单地允许括号适用于所有表达式（包含语句——因为语句现在也成了表达式）。于是：

```js
let v = ( if (x) 1; else 2 )
```
```js
let x = (
  let tmp = Math.random()
  tmp * tmp
)
```
本质上，这是把`;`变成了分号表达式——增强版的逗号表达式（区别是在优先级列表上，逗号表达式的优先级最低，而分号表达式的优先级几乎最高——仅次于括号）。

采用这种方案，其语义应该和 `eval`-based 是一样的，但没有`eval`的前例之后，是否要ban掉某些东西就都要费神去考虑。当然这也带来了最大的语义可能性，因为`eval`-based和*iife*-based都不应超出原本的语义限制。

这种方案的另一个问题是将来若要支持async，就不太能直接用`let x = async (expression)`（因为现在会被解析为对一个名为async的函数的调用），而需要特殊的语法，比如 `(async: expression)`。

另外的语法方案是，仍然使用基于花括号的语法。之所以不能 `let v = { if (x) 1; else 2 }`是因为当parser看到`{`的时候已经认为这是一个 object literal 了。注意 parser 是无法根据后续的token来主动区分 block 和 object literal 的，因为`{a: 1, b: 2}`也可以被解释为两个带有label的语句所构成的block。所以需要在`{`前后加入额外符号以区分。可能的方案比如使用双花括号 `let v = {{ if (x) 1; else 2 }}`或转义 `let v = \{ if (x) 1; else 2 }`，虽然从个人角度，这样的语法似乎还不如用括号。当前的提案语法 `do { ... }`可被视为类似的（不使用额外符号，而是使用关键字的）变种。`do {}`语法的问题主要是当和 `while` 循环混用时会有一些诡异的结果。对于parser来说是没有问题的，但是对于人来说，我们希望在`do {`开始的地方就知道这是一个 do expression 还是一个 `do ... while`。

---

一句话总结：do expression 的问题主要是语义预期和适配于语义的语法设计上。Maximally minimal 的方案可以暂时规避这些问题（选择了最小的语义子集），但即使可以由此进入 stage 2，在 stage 3 之前仍然需要厘清关键的方向性问题。

**Comment by maxloh** [comment]
如果在do block內有return statement會怎樣？

**Comment by Huxpro** [comment]
1, 2 隔靴搔痒，3 以及原 proposal 要面对的非正交的东西太多……
这个提案太难了

**Comment by hax** [comment]
@Huxpro 我们先要对do expression有个预期，这个东西到底是为了解决什么问题？其实如果考虑语言能力的话，它本来就是没有很大必要的，它的存在只是为了开发者体验——所以它本来的目标就是「搔痒」而已。那么我们的问题就是别越搔越痒甚至挠破就好了。比如我认为从表达式里进行流程跳转就是「挠破」了。😂
